### ISSUE TITLE
Ever thought of moving to Estonia?

### ISSUE THREAD

**Issue by ninjasort** [bsazonov/bsazonov.github.io#1]
Hey Boris,

How's all going? I was just curious if you ever thought of moving to Estonia. It's pretty cool out here and there are many jobs for developers. I think you would like it.

- Cameron

**Comment by bsazonov** [comment]
I currently don't have plans to move to Estonia, but thanks for asking!

**Comment by ninjasort** [comment]
Sure, no prob! Thanks for connecting on LinkedIn. :)
